pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/b-chetna/jenkins-exp.git'
            }
        }
        stage('Generate Report') {
            steps {
                dir('project2') {
                    bat 'python app.py'
                }
            }
        }
        stage('Archive Report') {
            steps {
                archiveArtifacts artifacts: 'project2/report.txt', fingerprint: true
            }
        }
    }
}
```
